### PR TITLE
Revamp reporter (2/2): handle json rpc down and server restart/crash

### LINKED ISSUE #1570: Improve processing time in vrf & rr
End to end execution time for fulfilling 50 events/requests in a single block for vrf & rr is 4+ mins. Here is a [slack discussion](https://bisonai.slack.com/archives/C04772WQ3DW/p1717583635243089).

The way processing time has been measured is as follows:
 - Start timer before sending a request to a consumer contract
 - Stop timer after all 50 requests have been fulfilled

### PR DESCRIPTION
**Pull request by Intizar-T**
# Description

Closes #1570 

Implements infinite polling in predefined intervals, currently 1 second, when json rpc goes down and `wallet.getTransactionCount()` operation fails in the nonce manager mutex function. There will be an error log and slack message at certain intervals, currently set to 10 mins, until the json rpc becomes available

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review

- [x] I have performed a self-review of my code.
- [ ] If it is a core feature, I have added thorough tests.

## Deployment

- [ ] Should publish npm package
- [ ] Should publish Docker image

### CODE REVIEW

File: core/src/reporter/state.ts [hunk 1]
```diff
@@ -294,38 +301,53 @@ export class State {
...
+            this.logger.error(
+              { name: 'getAndIncrementNonce', file: FILE_NAME },
+              `Error while fetching nonce for oracle ${oracleAddress}. Retrying...`
+            )
+            await sendToSlack(error)
+          }
+          retryCount += 1
+
+          // Sleep before retrying
+          await sleep(NONCE_MANAGER_POLLING_INTERVAL)
```
[the remark this answers is not in the document]
Comment (Intizar-T) [reply core/src/reporter/state.ts:348]: infinite loop is an intentional feature. This will prevent bullmq from marking in-progress jobs as failed. Once json rpc becomes responsive again, it'll fulfill those requests.

File: core/test/nonce-manager.test.ts [hunk 2]
```diff
@@ -62,7 +62,7 @@ describe('nonce-manager', () => {
     }
   })
 
-  test('cannot get transaction count', async () => {
+  test.skip('cannot get transaction count', async () => {
```
Comment (nick-bisonai) [inline core/test/nonce-manager.test.ts:65]: are you skipping because it falls into infinite loop?

**Comment by nick-bisonai** [comment]
made minor suggestion 😉:
https://github.com/Bisonai/orakl/pull/1617

File: core/test/nonce-manager.test.ts (hunk 2 above)
Comment (Intizar-T) [reply core/test/nonce-manager.test.ts:65]: yes, this is quite tricky to mock. I'll leave it as a todo for now. Will leave a comment

File: core/test/nonce-manager.test.ts [hunk 3]
```diff
@@ -62,7 +62,9 @@ describe('nonce-manager', () => {
     }
   })
 
-  test('cannot get transaction count', async () => {
+  // The following test is an outdated implementation, before infinite polling.
+  // Running this now will cause an infinite loop. It needs to be updated accordingly.
+  test.skip('cannot get transaction count', async () => {
```
[the remark this answers is not in the document]
Comment (nick-bisonai) [reply core/test/nonce-manager.test.ts:67]: 🥹

[the remark this answers is not in the document]
Comment (nick-bisonai) [reply core/test/nonce-manager.test.ts:67]: Can you show show me test code for infinite polling behavior

[the remark this answers is not in the document]
Comment (nick-bisonai) [reply core/test/nonce-manager.test.ts:67]: @Intizar-T  do you think this suggestion is acceptable?

File: core/src/reporter/state.ts [hunk 4]
```diff
@@ -276,10 +283,25 @@ export class State {
     return reporters
   }
 
+  async getRemoteNonce(wallet: Wallet): Promise<number> {
```
Comment (martinkersner) [inline core/src/reporter/state.ts:286]: @Intizar-T I think we could use this function inside of `refresh` as well.

https://github.com/Bisonai/orakl/blob/03d4bd22e901af24dc6bbaa17604f38bebc38d5c/core/src/reporter/state.ts#L258

File: core/src/reporter/state.ts [hunk 5]
```diff
@@ -294,35 +316,31 @@ export class State {
...
-            await caverWallet.caver.rpc.klay.getTransactionCount(caverWallet.address)
-          )
-        } else {
-          remoteNonce = await (wallet as NonceManager).getTransactionCount()
+      while (true) {
+        try {
+          remoteNonce = await this.getRemoteNonce(wallet)
+          break
+        } catch (error) {
+          // Slack the error message every half an hour
```
Comment (martinkersner) [inline core/src/reporter/state.ts:329]: @Intizar-T Where does the `half an hour` comes from? Is it correct?

Comment (martinkersner) [reply core/src/reporter/state.ts:329]: It is better to remove such comments since they become outdated as soon as externally defined constant is updated.

File: core/src/settings.ts [hunk 6]
```diff
@@ -245,3 +245,8 @@ export const NONCE_MANAGER_JOB_SETTINGS = {
 export function getObservedBlockRedisKey(contractAddress: string) {
   return `${contractAddress}-listener-${DEPLOYMENT_NAME}`
 }
+
+export const NONCE_MANAGER_POLLING_INTERVAL = 1_000 // ms
+export const NONCE_MANAGER_SLACK_FREQUENCY_TIME = 10 // min
+export const NONCE_MANAGER_SLACK_FREQUENCY_RETRIES =
+  (NONCE_MANAGER_SLACK_FREQUENCY_TIME * 60) / (NONCE_MANAGER_POLLING_INTERVAL / 1000)
```
Comment (martinkersner) [inline core/src/settings.ts:252]: @Intizar-T If you want to assign unit to a constant it is better to include it to constant name, otherwise, other developers can learn about it by coming to this file.

```suggestion
export const NONCE_MANAGER_POLLING_INTERVAL_MS = 1_000
export const NONCE_MANAGER_SLACK_FREQUENCY_TIME_MIN = 10
export const NONCE_MANAGER_SLACK_FREQUENCY_RETRIES =
  (NONCE_MANAGER_SLACK_FREQUENCY_TIME_MIN * 60) / (NONCE_MANAGER_POLLING_INTERVAL_MS / 1000)
```

File: core/src/reporter/state.ts [hunk 7]
```diff
@@ -294,35 +316,31 @@ export class State {
...
-        this.logger.warn(
-          { name: 'getAndIncrementNonce', file: FILE_NAME },
-          `Nonce value discrepancy. Remote: ${remoteNonce}, Local: ${localNonce}. Updating local nonce to remote nonce.`
-        )
-        nonce = remoteNonce
-      } else {
-        nonce = localNonce
-      }
-
+      const nonce = Math.max(this.nonces[oracleAddress], remoteNonce)
```
Comment (martinkersner) [inline core/src/reporter/state.ts:343]: @Intizar-T It seems that we fetch remote nonce for every new transaction and if we cannot fetch it we keep trying until the server responds. If that is true, I am not sure the local nonce mapping `this.nonces` has real purpose. Can you please share why do we need it? 🙏

File: core/test/nonce-manager.test.ts [hunk 8]
```diff
@@ -62,7 +62,9 @@ describe('nonce-manager', () => {
     }
   })
 
-  test('cannot get transaction count', async () => {
+  // The following test is an outdated implementation, before infinite polling.
```
Comment (martinkersner) [inline core/test/nonce-manager.test.ts:65]: @Intizar-T Let's udpate it in this PR, or let's remove it 🙏

File: core/src/reporter/state.ts (hunk 7 above)
Comment (Intizar-T) [reply core/src/reporter/state.ts:343]: good point Martin. I was trying to take care of a case where the wallet that we use to report makes a transaction outside this service (vrf or rr) and my local nonce will be outdated. Would you say that's a realistic scenario? Do we use the reporter wallets anywhere else outside the vrf/rr services? If not then it'll make things much easier. If yes, then I'll need to come up with a different approach to solve it.

Comment (martinkersner) [reply core/src/reporter/state.ts:343]: The only time we use it when we want to take earned KLAY out of the reporter, but that does not happen often. And if that happens, the current solution should fail and get new nonce reassigned.

Comment (Intizar-T) [reply core/src/reporter/state.ts:343]: got it. Then I'll simply catch the `NonceAlreadyUsed` error and retry with new nonce

File: core/src/reporter/state.ts (hunk 4 above)
Comment (Intizar-T) [reply core/src/reporter/state.ts:286]: since i've removed fetching remote nonce logic from local nonce manager, this function has been removed as well

File: core/src/utils.ts [hunk 9]
```diff
@@ -37,20 +37,35 @@ export function pad32Bytes(data) {
...
+      errorObj
     )} \`\`\`\n>*System information*\n>*memory*: ${os.freemem()}/${os.totalmem()}\n>*machine*: ${os.machine()}\n>*platform*: ${os.platform()}\n>*upTime*: ${os.uptime()}\n>*version*: ${os.version()}
    `
 
     try {
-      if (e && e.message && errMsg === e.message) {
+      // if the same error message is sent to slack before
+      if (e?.message && errMsg === e.message) {
         const now = new Date().getTime()
+        // if it's over 1 min since the last message was sent
```
[the remark this answers is not in the document]
Comment (Intizar-T) [reply core/src/utils.ts:68]: the logic there is to re-send the same message to slack after 1 min earliest. So we first check if the same error message has already been sent and if so has it been at least a minute since the last time it was sent. If all conditions met we resend the same error again

**Review by martinkersner — APPROVED** [review]
LGTM!

**Review by nick-bisonai — APPROVED** [review]
lgtm!
